import { StyleSheet } from 'react-native';
import { colors, spacing, borderRadius, withOpacity } from '../../../../theme';

export const styles = StyleSheet.create({
  contentContainer: {
    maxHeight: 400,
  },
  membersList: {
    maxHeight: 280,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  memberCountPill: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.divider,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  memberCountText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '700',
  },
  memberCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.divider,
    borderRadius: borderRadius.xl,
    padding: spacing.md,
    marginBottom: spacing.sm,
    gap: spacing.base,
  },
  memberAvatar: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
  },
  memberAvatarImage: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.full,
    backgroundColor: colors.background,
  },
  memberAvatarText: {
    fontSize: 14,
    color: colors.textLight,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  memberTextColumn: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  memberHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  memberName: {
    flex: 1,
    fontSize: 16,
    color: colors.textPrimary,
    fontWeight: '700',
  },
  memberEmail: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  memberMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  badge: {
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  currentUserBadge: {
    backgroundColor: withOpacity(colors.primary, 0.1),
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  currentUserBadgeText: {
    color: colors.primary,
  },
  roleBadge: {
    alignSelf: 'flex-start',
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  adminRoleBadge: {
    backgroundColor: withOpacity(colors.success, 0.12),
  },
  memberRoleBadge: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  roleBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  adminRoleBadgeText: {
    color: colors.success,
  },
  memberRoleBadgeText: {
    color: colors.textMuted,
  },
  removeIconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: borderRadius.full,
    backgroundColor: withOpacity(colors.error, 0.08),
  },
  removeIconButtonDisabled: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  actionSection: {
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  primaryActionButton: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: colors.primary,
    borderRadius: borderRadius.xl,
    paddingHorizontal: spacing.md,
  },
  primaryActionText: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textLight,
  },
  secondaryActionButton: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: colors.background,
    borderRadius: borderRadius.xl,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  secondaryActionText: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.primary,
  },
  inlineHelperText: {
    marginTop: spacing.xs,
    fontSize: 12,
    lineHeight: 17,
    color: colors.textMuted,
  },
  footer: {
    paddingTop: spacing.md,
    marginTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  footerText: {
    fontSize: 12,
    color: colors.textMuted,
    textAlign: 'center',
  },
  stateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xl,
    gap: spacing.sm,
  },
  stateText: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  inviteSection: {
    backgroundColor: colors.background,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginTop: spacing.lg,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  inviteCodeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
    minHeight: 48,
    marginTop: spacing.sm,
  },
  inviteCodeText: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: colors.primary,
    letterSpacing: 2,
    textAlign: 'center',
  },
  iconButton: {
    padding: spacing.sm,
  },
});
